// <auto-generated />
using System;
using JuguetylandiaWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JuguetylandiaWeb.Migrations
{
    [DbContext(typeof(JuguetylandiaContext))]
    [Migration("20190401175848_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JuguetylandiaWeb.Models.Juguete", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad");

                    b.Property<string>("Descripcion");

                    b.Property<string>("Ean");

                    b.Property<int>("Edad");

                    b.Property<DateTime?>("FechaGarantia");

                    b.Property<DateTime?>("FechaRecepcion");

                    b.Property<string>("InfoGarantia");

                    b.Property<int>("MarcaId");

                    b.Property<string>("Nombre")
                        .HasMaxLength(60);

                    b.Property<int>("Oferta");

                    b.Property<string>("PVP");

                    b.Property<string>("Referencia");

                    b.Property<int>("TiendaId");

                    b.Property<int>("Tipo");

                    b.HasKey("ID");

                    b.HasIndex("MarcaId");

                    b.HasIndex("TiendaId");

                    b.ToTable("Juguetes");
                });

            modelBuilder.Entity("JuguetylandiaWeb.Models.Marca", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("JuguetylandiaWeb.Models.Tienda", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .IsRequired();

                    b.Property<string>("Direccion");

                    b.HasKey("ID");

                    b.ToTable("Tiendas");
                });

            modelBuilder.Entity("JuguetylandiaWeb.Models.Juguete", b =>
                {
                    b.HasOne("JuguetylandiaWeb.Models.Marca", "Marca")
                        .WithMany("Juguetes")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JuguetylandiaWeb.Models.Tienda", "Tienda")
                        .WithMany("Juguetes")
                        .HasForeignKey("TiendaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
